In [1]:
import pyarrow.parquet as pq
import pandas as pd

#### Load the path to the prediction dataset. For each model API version, a new folder is created

In [2]:
# *** fill in your model version ID (found in versions tab, it is not the model ID) ***
#this is also found if you look at the contents of your predictions dataset

model_version_id= "6426faaa8cdc3c20deb356d6" 
#example model_version_id="618b7b8d4064b12fe8c31fdf"

#for DFS based projects the path starts with /domino/datasets/local
#path = '/domino/datasets/local/prediction_data/{}/'.format(model_version_id)


#for Git based projects the path starts with /mnt/data
path = '/mnt/data/prediction_data/{}/'.format(model_version_id)

#### Load the entire directory as a parquet object into a pandas dataframe

In [5]:
df = pd.read_parquet(path)

#### You can now query the dataframe for various ranges of data you might be interested in

In [6]:
df[(df['timestamp'] > '2023-3-10') & (df['timestamp'] < '2023-4-12')]

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,...,long,sqft_living15,sqft_lot15,price,event_id,timestamp,instance_id,__domino_timestamp,$$date$$,$$hour$$
0,1.41778,1.223533,1376.280841,-44282.091927,1.066314,-0.016425,-0.124127,3.010861,6.446309,1134.260142,...,-122.297386,1162.588196,-15814.149591,265000,6ba35d6e-8448-4d01-b930-ff02db9a259a,2023-03-31 15:28:05.771690+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T15:28:05.771713+00:00,2023-03-31Z,15Z
1,1.41778,1.223533,1376.280841,-44282.091927,1.066314,-0.016425,-0.124127,3.010861,6.446309,1134.260142,...,-122.297386,1162.588196,-15814.149591,265000,f8d49b32-ff93-426d-bee5-45c04677167d,2023-03-31 15:50:20.363067+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T15:50:20.363090+00:00,2023-03-31Z,15Z
2,9.02520,3.267600,1.307400,10.192200,1.952700,8.747100,2.334800,10.681600,4.277100,3.958700,...,4.681800,4.778200,8.580100,217000,e03c69c0-92c9-4fca-a21d-fcd3699c8620,2023-03-31 16:20:50.353966+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:20:50.353989+00:00,2023-03-31Z,16Z
3,4.47370,9.865000,6.441900,6.974300,8.992400,2.590600,6.464300,6.489300,5.486100,7.965200,...,4.541200,7.249100,7.934600,570000,69fe5bdf-8a5f-4575-8cb2-85ff8a128c74,2023-03-31 16:20:50.377108+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:20:50.377130+00:00,2023-03-31Z,16Z
4,7.69880,1.637800,3.512700,3.241800,8.557800,7.799700,7.078000,1.254300,7.820900,4.247600,...,5.834000,2.544800,2.283400,570000,33b7777c-4140-4b9b-8d4f-7eabb0585c3e,2023-03-31 16:20:50.398504+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:20:50.398526+00:00,2023-03-31Z,16Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,10.90050,2.981900,2.013900,6.631500,7.322700,3.341100,3.174200,8.293900,5.829400,5.706200,...,10.471000,6.055400,9.862500,570000,28b664ef-3ff5-46e8-a294-018e7b1304e5,2023-03-31 16:50:58.823765+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:50:58.823785+00:00,2023-03-31Z,16Z
198,7.45680,1.102000,5.757300,7.944500,7.291700,7.914700,5.545000,8.173500,5.675500,9.561300,...,9.150500,7.473800,7.534100,570000,acf1efb3-dbad-4d8d-bb6d-f7d9a6c49b7f,2023-03-31 16:50:58.843801+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:50:58.843821+00:00,2023-03-31Z,16Z
199,8.47040,3.285300,2.411700,1.418000,8.579300,6.017300,10.707300,6.444600,8.740200,9.038500,...,1.035600,3.414900,4.093400,770000,a58ab24a-bd7e-488d-9af5-3dcf6fc4da0c,2023-03-31 16:50:58.864357+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:50:58.864376+00:00,2023-03-31Z,16Z
200,4.38560,8.878300,9.779100,10.658100,10.271100,1.299500,2.142800,7.681200,9.042400,9.152900,...,7.390200,5.364000,1.818500,770000,26bd6ec6-91a5-4512-a075-5da8d03d70d2,2023-03-31 16:50:58.889037+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:50:58.889057+00:00,2023-03-31Z,16Z
201,7.70300,6.654300,6.258400,7.405600,9.275600,2.991200,1.120700,1.455600,1.179200,1.033400,...,1.262100,7.146800,9.177000,217000,5b407ce8-ee5a-437d-a7ca-b42ba19e7267,2023-03-31 16:50:58.910173+00:00,6426faaa8cdc3c20deb356d6,2023-03-31T16:50:58.910192+00:00,2023-03-31Z,16Z

In [7]:
#Download the predictions to use as the base for ground truth data
#for DFS based projects the path starts with /mnt/results
#df.to_csv('/mnt/results/preds_from_domino.csv')

#for Git based projects the path starts with /mnt/artifacts/results
df.to_csv('/mnt/artifacts/results/preds_from_domino.csv')